### ISSUE TITLE
gitignore 파일 추가 필요.

### ISSUE THREAD

**Issue by malkoG** [reverince/TIL#1]
JS 로 개발하다보면 node_modules 파일만 몇십-몇백 메가바이트씩 쌓이는데, 이런 것들을 깃헙 리포지토리에 하나하나 다 올리면 나중에 업데이트하거나 다운로드 받을때 상당히 느려져요...... node modules 디렉토리만 골라서 `git rm -rf` 해주시고 gitignore 파일 관리도 좀 해주셔야 할 듯 해요.

**Comment by reverince** [comment]
우오 감사합니다 해보겠습니다.
